# Generated by Django 3.1.1 on 2021-07-21 04:51

import botmother.utils.api
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_id', models.BigIntegerField(blank=True, null=True)),
                ('latitude_from', models.FloatField(blank=True, null=True)),
                ('longitude_from', models.FloatField(blank=True, null=True)),
                ('address_text', models.CharField(blank=True, max_length=255, null=True)),
                ('address_latitude', models.FloatField(blank=True, null=True)),
                ('address_longitude', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('mark', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_customer', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Booking',
            },
        ),
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_id', models.BigIntegerField(blank=True, null=True)),
                ('latitude_from', models.FloatField(blank=True, null=True)),
                ('longitude_from', models.FloatField(blank=True, null=True)),
                ('address_text', models.CharField(blank=True, max_length=255, null=True)),
                ('address_latitude', models.FloatField(blank=True, null=True)),
                ('address_longitude', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('mark', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_customer', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'BookingHistory',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
                ('type', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_action', models.CharField(max_length=255, null=True)),
                ('data', models.TextField(null=True)),
                ('last_activity', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'bot_chats',
                'abstract': False,
            },
            bases=(models.Model, botmother.utils.api.TelegramAPI),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_id', models.BigIntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.BigIntegerField(blank=True, null=True)),
                ('car', models.CharField(blank=True, max_length=255, null=True)),
                ('color_of_car', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_car', models.CharField(blank=True, max_length=255, null=True)),
                ('ready', models.BooleanField(default=False)),
                ('busy', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Driver',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_id', models.BigIntegerField(blank=True, null=True)),
                ('type', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_action', models.CharField(max_length=255, null=True)),
                ('data', models.TextField(null=True)),
                ('last_activity', models.DateTimeField(auto_now_add=True, null=True)),
                ('number', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Users',
            },
        ),
    ]
